### ISSUE TITLE
我就不明白绳子太长就会打结，而你的舌头却不能

### ISSUE THREAD

**Issue by Hny0305Lin** [anrui2032/anrui2032#1]
![V9 WBQG%)@B {ZFB21QK$K0](https://user-images.githubusercontent.com/51528915/129033455-c8dc8fde-6694-46b0-bb1a-eacc09093d07.png)

**Comment by Hny0305Lin** [comment]
合着大家用的Ubuntu20.04好好的，一颗老鼠屎来脏了这个圈

**Comment by anrui2032** [comment]
您好，对不起啊，只是句玩笑话，如果您比较在意的话我想您和我说的话道歉

**Comment by Hny0305Lin** [comment]
互联网可不是没有记忆吖小孩子/笑哭 你知道这句话得寒了多少热爱Ubuntu小可爱的心嘛

**Comment by Hny0305Lin** [comment]
就这样吧，我也不是那种要追查到底的人，以后注意点言辞

**Comment by anrui2032** [comment]
抱歉啊，我的意思只是这机器狗没有用上20.04，当然我自己也在用20.04的serverf服务器端

**Comment by anrui2032** [comment]
好的
